using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

public class Sensor : MonoBehaviour
{
    public MxComponent mxComponent;
    public int isSensing;
    public int PLCOutput;
    public int isChange;

    void Start()
    {
        isSensing = 0;
        PLCOutput = 0;
        isChange = 0;
        
    }

    void Update()
    {
        
    }

    private void OnTriggerEnter(Collider other)
    {
        if(other.gameObject.layer == LayerMask.NameToLayer("CylinderPoint"))
        {
            if (isSensing == 0)
            { 
                isChange = 1;
                PLCOutput = 1;
                isSensing = 1;
            }
        }
        if (other.gameObject.layer == LayerMask.NameToLayer("Box"))
        {
            if (isSensing == 0)
            {
                isChange = 1;
                PLCOutput = 1;
                isSensing = 1;
            }
        }

        if (name.Contains("Sensor8"))
        {
            mxComponent.Write($"R,D22");

            StartCoroutine(CoSaveCoordinates());
        }
    }

    IEnumerator CoSaveCoordinates()
    {
        yield return new WaitUntil(() => mxComponent.isDReceived == true);


        mxComponent.LoadingCylinderHY.GetComponent<LoadingCylinder>().HighDistance = mxComponent.decimalNumbers[7];
        mxComponent.Write($"W,{"X20"},{mxComponent.LoadingCylinderY.GetComponent<LoadingCylinder>().BackEndIndex},");
        print($"W,{"X20"},{mxComponent.LoadingCylinderY.GetComponent<LoadingCylinder>().BackEndIndex},");

        /*  촥킨 찣쫚
        distance = mxComponent.decimalNumbers[0]; // D22 : 炷！ x 촥킨
        distance = mxComponent.decimalNumbers[1]; // D23 : 炷！ y 촥킨
        distance = mxComponent.decimalNumbers[2]; // D24 : 炷！ z 촥킨
        distance = mxComponent.decimalNumbers[10]; // D32 : 炷＂ x 촥킨
        distance = mxComponent.decimalNumbers[11]; // D33 : 炷＂ y 촥킨
        distance = mxComponent.decimalNumbers[12]; // D34 : 炷＂ z 촥킨
        mxComponent.decimalNumbers[5] : 炷 1, 2 쏮쥃 -> 1 = 炷！ , 0 = 炷＂ */

        if (mxComponent.decimalNumbers[5] == 1)
        {
            mxComponent.LoadingCylinderX.GetComponent<LoadingCylinder>().distance = mxComponent.decimalNumbers[0];
            mxComponent.LoadingCylinderY.GetComponent<LoadingCylinder>().distance = mxComponent.decimalNumbers[1];
            mxComponent.LoadingCylinderZ.GetComponent<LoadingCylinder>().distance = mxComponent.decimalNumbers[2];
        }

        if (mxComponent.decimalNumbers[5] == 0)
        {
            mxComponent.LoadingCylinderX.GetComponent<LoadingCylinder>().distance = mxComponent.decimalNumbers[10];
            mxComponent.LoadingCylinderY.GetComponent<LoadingCylinder>().distance = mxComponent.decimalNumbers[11];
            mxComponent.LoadingCylinderZ.GetComponent<LoadingCylinder>().distance = mxComponent.decimalNumbers[12];
        }

        mxComponent.isDReceived = false;
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.gameObject.layer == LayerMask.NameToLayer("CylinderPoint"))
        {
            if (isSensing == 1)
            {
                isChange = 1;
                PLCOutput = 0;
                isSensing = 0;
            }
        }
        if (other.gameObject.layer == LayerMask.NameToLayer("Box"))
        {
            if (isSensing == 1)
            {
                isChange = 1;
                PLCOutput = 0;
                isSensing = 0;
            }
        }
    }
}
